### ISSUE TITLE
PlayerDataStore returning table instead of number?

### ISSUE THREAD

**Issue by kinkocat** [Quenty/NevermoreEngine#126]
Is this a bug? Unfinished? Or am i doing something wrong? Is there some code or documentation i can look at to answer my question? (Sorry if this is the wrong place to post this, didn't want to post it on the devforum since its strictly related to nevermore.)

The problem i am having is that PlayerData:Load("Money", 500) in my case returns  a table rather than the saved value in the DataStore or even the default value. If this is correct, how am i supposed to get the stored value?

```lua
local Players 					= game:GetService("Players")
local ReplicatedStorage 		= game:GetService("ReplicatedStorage")
local DataStoreService 			= game:GetService("DataStoreService")
local ServerStorage 			= game:GetService("ServerStorage")
local MarketplaceService		= game:GetService("MarketplaceService")
local Teams						= game:GetService("Teams")

local Engine 					= require(ReplicatedStorage:WaitForChild("Nevermore"))
local require 					= Engine.require

local DataStoreManager			= require("PlayerDataStoreManager")

local DataStore = DataStoreService:GetDataStore("PlayerData")	
local PlayerDataStore = DataStoreManager.new(DataStore, function(Player)
	return "/" .. Player.UserId .. "/"
end)

local function PlayerAdded(Player)

	local PlayerData = PlayerDataStore:GetDataStore(Player)
	
        -- These values are just instanced in a seperate script.
	local Leaderstats = Player:WaitForChild("leaderstats")
	local Money = Leaderstats:WaitForChild("Money")
	Money.Value = PlayerData:Load("Money", 500) -- Won't add the saved value or the default value due to it returning a table.
	
	PlayerData:StoreOnValueChange("Money", Money)
end

for i,v in pairs(Players:GetPlayers()) do
	PlayerAdded(v)
end

Players.PlayerAdded:Connect(PlayerAdded)
```

**Comment by Quenty** [comment]
You’re using it wrong, sorry! It returns a promise! 

I’m on mobile but will type out a better answer later. 

You want to do this:

PlayerData:Load(“Money”, 500):Then(function(money)
    Money.Value = money
        PlagerData:StoreOnValueChanged(“Money”, Money) — Only store if we load properly 
end):Catch(function(err) — handle 

end)

**Comment by kinkocat** [comment]
Oh, thank you! I understand how promises work now so i can utilize more aspects of the engine. Thanks for the example (:
