### ISSUE TITLE
Installation error due to malformed links

### ISSUE THREAD

**Issue by colbert2677** [Quenty/NevermoreEngine#138]
Upon running the installer, an exception is thrown and points towards lines 63 and 86. The exception in question is as follows:

> **HttpError: InvalidUrlhttps://github.comhttps://github.com/Quenty/NevermoreEngine/tree/version2/Modules**

I suspect that the issue is the GitHub installer function automatically appending the GitHub URL to a given installer directory, so it ends up repeating itself in the link. This can be seen beside "InvalidUrl" where GitHub is repeated twice.

Have not made a pull request because I haven't looked through the source myself or figured out a fix, so raising an issue instead.

**Comment by Quenty** [comment]
This should be fixed now! Please comment if it isn't!
