### ISSUE TITLE
ServerScriptService.Nevermore doesn't exist

### ISSUE THREAD

**Issue by Masken8** [Quenty/NevermoreEngine#142]
ServerScriptService.Nevermore doesn't exist on fresh install
![image](https://user-images.githubusercontent.com/26001144/77177697-3dbbad00-6ac6-11ea-891d-ce92da27c158.png)
![image](https://user-images.githubusercontent.com/26001144/77177747-55933100-6ac6-11ea-8be5-82c12b9e6d76.png)

**Comment by kieranz** [comment]
Yeah, it's called NevermoreEngine, I made a pull request.

**Comment by Quenty** [comment]
I just updated the installer to install as "Nevermore" which is what every script expects.
