### ISSUE TITLE
Add support for alternative casing

### ISSUE THREAD

**Issue by sayhisam1** [Quenty/NevermoreEngine#147]
Referencing https://github.com/Roblox/rodux/issues/48

It would be helpful to support both "disconnect" and "destroy" as alternative cases used in the maid class, since these conform to the camelCase naming convention used by popular libraries such as rodux.

**Comment by Quenty** [comment]
Probably won't fix this one. This adds a lot of documentation and clarity burden, and makes refactoring harder. If you want to add a wrapper to automatically generate this, it should not be too much code.
