### ISSUE TITLE
NevermoreEngine errors whenever I try using a module

### ISSUE THREAD

**Issue by Hoidberg** [Quenty/NevermoreEngine#161]
<details>
  <summary><strong><em>Whenever I try using a module I get this error:</em></strong></summary>

  <h4><code>ReplicatedStorage.Nevermore.ModuleScriptLoader:66: Error: Library 'ScrollingFrame' does not exist</code></h4>
</details>
I tried reinstalling Nevermore Engine but it still didn't work

**Comment by howmanysmall** [comment]
I'll take a look.

**Comment by Hoidberg** [comment]
ScrollingFrame

**Comment by Hoidberg** [comment]
I was trying to test one of the examples

**Comment by Hoidberg** [comment]
Here it is:
```lua
local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

local ScrollingFrame = require("ScrollingFrame")
local Scrollbar = require("Scrollbar")

local scrollingFrame = ScrollingFrame.new(script.Parent)
scrollingFrame:AddScrollbar(Scrollbar.fromContainer(script.Parent.ScrollbarContainer))
```

**Comment by howmanysmall** [comment]
Ah. You need to have a script on the server requiring Nevermore first.

```lua
require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))
```

**Comment by Hoidberg** [comment]
But it errors for all libraries

**Comment by howmanysmall** [comment]
Did you require Nevermore on the server?

**Comment by Hoidberg** [comment]
no :man_facepalming:

**Comment by howmanysmall** [comment]
It's okay, I forget to do that too sometimes. Don't let it get to you. :P

**Comment by Hoidberg** [comment]
Thanks

**Comment by howmanysmall** [comment]
No problem. You can close it now.
