### ISSUE TITLE
Lazy load modules

### ISSUE THREAD

**Issue by JetCrusherTorpedo** [Quenty/NevermoreEngine#17]
Here is a suggestion:

* Store all modules in ServerStorage.
* Require all modules server-side and store the objects returned by the modules in a table.
* Clients request modules via a RemoteFunction, and the server returns the pre-compiled modules from the table mentioned above.
* Modules are memoized by the client when they are requested for the first time, eliminating the need for the module to be downloaded again, should the client need to require it more than once.

Memoization library: https://github.com/kikito/memoize.lua

**Comment by Quenty** [comment]
Good idea. Technically unfeasible.

ROBLOX RemoteFunctions cannot pass closures, functions, scopes, or metamethods for technical reasons, making this idea, although good, impossible to execute.
