### ISSUE TITLE
Installer doesn't create any script files

### ISSUE THREAD

**Issue by ozzyDrive** [Quenty/NevermoreEngine#183]
Running the installer with the command in README only creates three empty folders. It doesn't error and the prints go all the way to "Done installing Nevermore".
![image](https://user-images.githubusercontent.com/16411382/110139057-4bec0180-7ddb-11eb-8b8a-c8aae8624653.png)

I copied the installer source into a script to debug and found the HTTP request returns an empty body:
![image](https://user-images.githubusercontent.com/16411382/110138889-1e9f5380-7ddb-11eb-964f-a8f7896ca4d8.png)

**Comment by neeleythere** [comment]
I am also experiencing this issue.

The HTTP request returns an empty body.

**Comment by InvisibleWater** [comment]
It looks like there's an error somewhere that's preventing it from creating modules.

I ran a modified version of the installer script that printed the request body, and it caused [this](https://pastebin.com/UPVTFtKM) to show up in my output.

When I copied and pasted the text to an HTML file and opened it in my browser, this appeared:
![image](https://user-images.githubusercontent.com/26887549/111744750-1676f780-8862-11eb-8372-6f04c09d41a1.png)

**Comment by Quenty** [comment]
Fixed!
