### ISSUE TITLE
Infinite yield possible on 'ReplicatedStorage:WaitForChild("_replicationFolder")

### ISSUE THREAD

**Issue by julianhak** [Quenty/NevermoreEngine#186]
![image](https://user-images.githubusercontent.com/75813720/112064057-be2d4780-8b38-11eb-9947-e3a80feba3da.png)

The problematic code is:

![image](https://user-images.githubusercontent.com/75813720/112064078-c84f4600-8b38-11eb-9739-eed13b016c03.png)
(Line 87)

**Comment by howmanysmall** [comment]
Did you require it on the server too?

**Comment by julianhak** [comment]
Nope, just client

**Comment by howmanysmall** [comment]
You need to require it on the server.

**Comment by julianhak** [comment]
I believe that fixed the problem. It's attempting to call a nil value, but I think that's just my fault. Thanks
