### ISSUE TITLE
Support for Luau types

### ISSUE THREAD

**Issue by Rudy-Dev** [Quenty/NevermoreEngine#205]
I wonder if support for Luau Types is planned. I think It would be a very nice thing, especially with the new Luau-powered autocomplete.

**Comment by howmanysmall** [comment]
the types don't play with nevermore so probably not

**Comment by Quenty** [comment]
I would like to support typing, especially if it can be provided via a t.ds style format, or if selene/other syntax highlighers support Luau and integration.

By versioning packages we should be able to get types without breaking a ton of stuff. Also, I'm working on making sure types play nicer with Nevermore in the future.
