### ISSUE TITLE
qTime should be archived, as it is outdated and inaccurate

### ISSUE THREAD

**Issue by Narrev** [Quenty/NevermoreEngine#23]
os.date() should completely take its place. My pull requests replace qTime with os.date()

**Comment by Quenty** [comment]
Definitely, once we resolve os.date()

Note to do this, we'll need to scrub qTime from the existing codebase and deprecate it for games that aren't using qTime.

**Comment by Quenty** [comment]
See this https://github.com/Quenty/NevermoreEngine/pull/22 for more details. Will be accepted once we resolve issue #33

**Comment by Narrev** [comment]
qTime has been scrubbed from existing codebase. Let's remove it?
