### ISSUE TITLE
:Once() method for Signal

### ISSUE THREAD

**Issue by OttoHatt** [Quenty/NevermoreEngine#263]
**What package is this for?**
[Signal](https://github.com/Quenty/NevermoreEngine/tree/main/src/signal).

**Describe your problem**
Roblox are adding a [`:Once(fn)` method to RBXScriptSignal](https://developer.roblox.com/en-us/resources/release-note/Release-Notes-for-531#changes).

**Describe the solution you'd like**
It'd be nice to mirror the API! I've always thought of Signal as a drop-in replacement.

**Comment by OttoHatt** [comment]
I can make a PR for this later, should be very simple?

**Comment by Quenty** [comment]
Yeah, this is good! I'll add it, or feel free to submit a PR!
