### ISSUE TITLE
SoftShutdown suggestions

### ISSUE THREAD

**Issue by Milo123459** [Quenty/NevermoreEngine#266]
**What package is this for?** SoftShutdown

**Describe your problem** The ability to customise how it works

**Describe the solution you'd like**

Something to control how players in that server are created. For example:
I am in place B with 5 of my friends. When a shutdown comes through, it should shutdown and request a new private server and teleport my 5 friends to that server.

**Comment by Quenty** [comment]
Soft shutdown will already attempt to guarantee that players playing in the same server are teleported back and forth as a group. This should cover the scenario!

Great suggestion though!
