### ISSUE TITLE
Better possible methods for calling Nevermore Engine

### ISSUE THREAD

**Issue by Narrev** [Quenty/NevermoreEngine#28]
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local NevermoreEngine   = require(ReplicatedStorage:WaitForChild("NevermoreEngine"))
local LoadCustomLibrary = NevermoreEngine.LoadLibrary
```

```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local LoadCustomLibrary = require(ReplicatedStorage:WaitForChild("NevermoreEngine")).LoadLibrary
```

Or wouldn't it make sense to make NevermoreEngine return LoadLibrary so we only need to say
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local LoadCustomLibrary = require(ReplicatedStorage:WaitForChild("NevermoreEngine"))
```
I realize Nevermore Engine includes GetRemoteEvent and GetRemoteFunction, but I think I should at least bring up the idea. You could put GetRemoteEvent and GetRemoteFunction inside of LoadCustomLibrary (because they are less used):
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local LoadCustomLibrary = require(ReplicatedStorage:WaitForChild("NevermoreEngine"))

-- optional and not used as frequently (I think?)
local GetRemoteEvent = LoadCustomLibrary("GetRemoteEvent")
local GetRemoteFunction = LoadCustomLibrary("GetRemoteFunction")
```

**Comment by Quenty** [comment]
This is a good idea. Another idea is to set NevermoreEngine's metatable `__call` metamethod so we can do
```
local LoadCustomLibrary = require(ReplicatedStorage:WaitForChild("NevermoreEngine"))
```

While still maintaining backwards compatibility. 

Narrev, you're correct in that GetRemoteEvent and GetRemoteFunction are both external elements. I think for now we can write these modules and then slowly move this API into these factor.

If you're ok with this, I'll assign you the task of writing and testing these elements before we begin to translate core elements into using this method.

Once you've added these, I'll modify Nevermore to be callable and start modifying core calls to Nevermore.

**Comment by Narrev** [comment]
What do you think about [this](https://github.com/Vorlias/ROBLOX-ModRemote) module? I think it has some cool features, and I don't know really what you would like added.
