### ISSUE TITLE
Chat:FilterForPlayerAsync isn't used in the Pseudo Chat module.

### ISSUE THREAD

**Issue by Dudemanjude** [Quenty/NevermoreEngine#31]
The Pseudo chat needs to use ROBLOX's filter for the chat. Or else it doesn't have the correct filters.

**Comment by Quenty** [comment]
There are some performance issues with fixing this. We'll need to execute these requests in parallel for each player. Please use `coroutines` for this, as `spawn()` and `delay()` both yield one Lua resume frame on chat.

**Comment by Quenty** [comment]
PseudoChat removed in version2.
