### ISSUE TITLE
No unified style

### ISSUE THREAD

**Issue by Quenty** [Quenty/NevermoreEngine#51]
We need to unify syntactic style within NevermoreEngine to make contributing later. 
- Wiki post with specification

**Comment by Narrev** [comment]
I opened a new Wiki page. Check it out, critique it, move stuff around, and think about it!
https://github.com/Quenty/NevermoreEngine/wiki/Code-Design-Specifications

**Comment by devSparkle** [comment]
You could consider writing both a `CONTRIBUTING.md` and creating a `gh-pages` branch where you could document the API.

**Comment by Narrev** [comment]
That's a great idea! Should we remove most of the READMEs and just use the wiki to show how to use the modules?

**Comment by devSparkle** [comment]
I think we should divide information into sections:

## Readme and Contributing

This is usually the first document the users see. We should place a link to the  `gh-pages` webpage (hosted with GitHub Pages). Users should direct here for information on how to install, and API reference. We should also place a link to `CONTRIBUTING.md`.

## GitHub Pages

This should be the face of Nevermore. The page should start by informing the users of the highlight features of the framework. It should also contain easy-to-use instructions for installation.

We should also consider creating a page for known-compatibility modules. Both inside this repository, and outside. This could be easily done by using a JSON file to store the information (a lot of possibilities to explore on this one, I recommend further discussion). A great example of this method of loading would be the [Microsoft on GitHub](https://microsoft.github.io/) page.

## Wiki

The wiki could be approached in two ways; we use the Website completely for all documentation purposes, or we could use the wiki for details that are only relevant to contributors.

There is also a third possibility of using the wiki to host `.md` files, that would then be used to display the website (seeing as the wiki is a repo itself).

**Comment by Quenty** [comment]
This issue is now solved with CONTRIBUTING.md specifying documentation style, and style across the codebase unified.
