### ISSUE TITLE
Example code does not work.

### ISSUE THREAD

**Issue by ToastEngine** [Quenty/NevermoreEngine#57]
I used the installer, and copy pasted the code from the example.
error: 21:36:53.578 - Workspace.Script:4: attempt to call local 'LoadCustomLibrary' (a table value)

Did some testing, To fix this issue use 
local qSystems = LoadCustomLibrary.LoadLibrary("qSystems")

**Comment by Narrev** [comment]
Make sure you are loading it using the method of this repository
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Nevermore = require(ReplicatedStorage:WaitForChild("NevermoreEngine")
local LoadCustomLibrary = Nevermore.LoadLibrary

**Comment by ToastEngine** [comment]
ah I see
