### ISSUE TITLE
Dehat and RemoveForceField do not work.

### ISSUE THREAD

**Issue by ToastEngine** [Quenty/NevermoreEngine#58]
Dehat and RemoveForceField do not work in RawCharacter?

Loop checking to see if qSystems.CheckCharacter(Player) returns true it does, meaning that in theory character is valid for further methods that use CheckCharacter which is not the case
for Dehat and RemoveForceField.

Source:
CharacterSpawned.OnClientEvent:connect(function()
	Logging.Log(2, "Player connected to server.")	
	repeat
		wait(1/60)
		Logging.Log(2, "qSystems.CheckCharacter(Player) returned "..tostring(qSystems.CheckCharacter(Player)))
	until qSystems.CheckCharacter(Player) 
	Logging.Log(2, "Character connected to server.")	
	Humanoid.WalkSpeed = 0
	Humanoid.JumpPower = 0
        qChar.Dehat(Character)
	qChar.RemoveForceField(Character)
end)

Incase you don't know what my Logging Module is.
--[[
Personal Logging Module, by Voltoxus	

Implementation:
	local Logging = require(/path/)
	Logging.SetPrefix("[CoreGame]: ")
	
	Logging.Log(1,"This is a message")
	output> [CoreGame]: This is a message
	
	Logging.Log(2, "This is a debug message")
	output> [DEBUG][CoreGame]: This is a message
	
	Logging.Log(3, "This is a message")
	output> [ERROR][CoreGame]: This is a message
	
	Logging.Log(4, "This is a critical message")
	output> [CRITICAL][CoreGame]: This is a message
--]]
		
OUTPUT: 
[DEBUG][Client] qSystems.CheckCharacter(Player) returned true
[DEBUG][Client] Character connected to server.
[CheckCharacter] - Character Check failed! ReplicatedStorage.NevermoreResources.Modules.Character:34: [Character] - The character did not have a correct head, torso, or humanoid, so 'Dehat' could not execute

Similar one for RemoveForceField

**Comment by Narrev** [comment]
We're still in the process of rewriting the codebase. The code here is many years old so it is a bit outdated and hasn't really been maintained. If you'd like to submit a pull request, you definitely can, but the new version of Nevermore will work much better as it develops

**Comment by a-kile** [comment]
:3 Is this project being worked on?

**Comment by ToastEngine** [comment]
@a-kile 
Yes, Its very useful, too I love it.

**Comment by ToastEngine** [comment]
@Narrev 
I don't know much about github, whats a pulling request?

**Comment by Quenty** [comment]
I'm also rewriting the project, using a new mixin system that has interesting design and performance implications.

I'll try to branch the project when I feel like it's semi-stable.

**Comment by Narrev** [comment]
Woah there. What are you rewriting?

**Comment by Quenty** [comment]
A lot of things I don't like.

**Comment by Narrev** [comment]
Care to elaborate a little?

**Comment by Quenty** [comment]
Yeah. 

- Removing libraries with "q" in front of them
- qSystems got deleted
- Removing unnecessary libraries
- Moving into a Mixin system which dynamically allocates mixed in interactive items
- Attempting to opensource several new components (dialog, UI elements)
- Keeping xBox, mobile support in newly updated components
- Removing administration and chat command systems
- Removing a lot of unnecessary or old API

**Comment by buoyantair** [comment]
Oh man O.O

**Comment by Narrev** [comment]
I've been working on some UI elements for open-sourcing as well.

**Comment by jackyloz** [comment]
Quenty, have any speculation on as to when you will branch it? I'm using Nevermore for many of my games, and it's amazing, but unfortunately it is sort of-kind of-outdated in a sense.

**Comment by devSparkle** [comment]
@jackyloz have you checked out @Narrev and my [version of Nevermore](https://github.com/NevermoreFramework/Nevermore)?

**Comment by Quenty** [comment]
These APIs are now removed.
