### ISSUE TITLE
Author in the document header

### ISSUE THREAD

**Issue by devSparkle** [Quenty/NevermoreEngine#63]
This may seem like a meaningless caveat, however, should we comment the username of the file author in the header of the file?

After all, this is GitHub and we can see the versioning history of a file and browse trough it's contributors. There should be no need to reference the original author unless the file is being imported by a user who is not itself the author of the file.

**Comment by Narrev** [comment]
Go with your gut

**Comment by Quenty** [comment]
Personally I would say no. It's just a habit I've ended up with since roblox scripts usually don't ship with source control

**Comment by Narrev** [comment]
@Quenty Review my pull request! Answer your email or check Skype once in a while too!

**Comment by Quenty** [comment]
Removed @author, see CONTRIBUTING.md for more details. Also, anything not in Legacy/ is now documented consistently.
