### ISSUE TITLE
PaperRipple BackgroundTransparency is unnatural

### ISSUE THREAD

**Issue by Validark** [Quenty/NevermoreEngine#66]
Here is a log of `BackgroundTransparency` recorded every `RenderStepped`, beginning at the time of the ButtonDown on a PaperRipple.
```
0.75
0.75027942657471
0.76328164339066
0.7765901684761
0.78976458311081
0.80342751741409
0.81690329313278
0.83032858371735
0.8434551358223
0.85710829496384
0.8698924779892
0.88332211971283
0.89692860841751
0.91028100252151
0.92343503236771
0.92985087633133
0.92480701208115
0.9199047088623
0.91480189561844
0.90997123718262
0.90489435195923
0.8997848033905
0.89477759599686
0.8898748755455
0.88448882102966
0.87995713949203
0.8748927116394
0.8695946931839
1
```

As you can see, it jumps almost `0.15` at the end

Source of issue:
https://github.com/Quenty/NevermoreEngine/blob/master/Modules/qGUI/PaperRipple/Ripple.lua#L150

**Comment by jackyloz** [comment]
Noticed how it makes a sharp turn to transparent when not completely holding down. Bugs me so much I just commented the line that changes transparency so all I get is the ripples. Not too shabby but not the full effect.

**Comment by Narrev** [comment]
I don't know. There are a lot of "interpretations" when it comes to material design. Quenty's is based off of Polymer's implementation. From the projects I've seen, I think material-ui.com has the best-looking implementation. I started on a module translating it to Lua and got pretty far, actually, but never finished it. It works but doesn't have API and isn't revised or organized. I might release a full library at some point, but it is difficult if it is just me working on it

**Comment by Narrev** [comment]
This isn't a bug, it's actually part of polymer as far as I know. Unless you translated the equations incorrectly, which it doesn't look like you did (aside from my pull request)

**Comment by Quenty** [comment]
Yeah, that's sorta weird. Probably a bug with Polymer.

**Comment by Quenty** [comment]
TODO: Look into Android Material Design spec and identify correct behavior.

**Comment by jackyloz** [comment]
@Quenty Did ya look into the Design spec yet? :/

**Comment by Validark** [comment]
(no)
