### ISSUE TITLE
Add projectile and particle modules

### ISSUE THREAD

**Issue by Sanjay-B** [Quenty/NevermoreEngine#67]
Many users struggle with coding working projectiles and advanced particles. It would be nice to see it in this project.

**Comment by devSparkle** [comment]
I know for sure @Quenty has developed modules to handle projectile physics. Perhaps this is something that could be open-sourced?

**Comment by Quenty** [comment]
Already open source.

https://github.com/Quenty/NevermoreEngine/blob/6f303d12ac079895359adea7c986fe7122e19625/Modules/Physics/ProjectilePhysics.lua
