### ISSUE TITLE
BezierFactory.lua is based on deprecated files

### ISSUE THREAD

**Issue by Validark** [Quenty/NevermoreEngine#69]
Deprecated version:
https://gist.github.com/gre/1926947#file-keyspline-js

Here is the recommended version:
https://github.com/gre/bezier-easing

**Comment by Validark** [comment]
I also think the module should be called `Bezier` and curves should be created with `Bezier.new`

**Comment by Quenty** [comment]
I think leaving it as a function factory is fine in this case, since it's output is a function. TODO:

* Rename to Bezier.lua
* Update source code to follow recommended version

**Comment by Validark** [comment]
I'm saying I think the use of the module should look like this
```lua
-- Taken from material.io motion guidelines
local Sharp = Bezier.new(0.4, 0, 0.6, 1)
local Standard = Bezier.new(0.4, 0, 0.2, 1)
local Acceleration = Bezier.new(0.4, 0, 1, 1)
local Deceleration = Bezier.new(0, 0, 0.2, 1)
```

**Comment by Quenty** [comment]
That's fair.
