### ISSUE TITLE
Nevermore isn't working..

### ISSUE THREAD

**Issue by ittehgeps** [Quenty/NevermoreEngine#88]
I was trying to get snackbars to work in play mode and this happend:  
![console error](https://user-images.githubusercontent.com/36374487/37205543-2274cf60-2363-11e8-8f2d-2a9bebd768ca.PNG)

**Comment by Quenty** [comment]
Make sure you require `Nevermore` from a server script! Just put it in `ServerScriptService`

**Comment by ittehgeps** [comment]
But i need to use it on the client..

**Comment by ittehgeps** [comment]
k, it sorta worked... but then this happened: 
![dsfsf](https://user-images.githubusercontent.com/36374487/37249945-7e1cc8c4-24bf-11e8-856b-c9d877317d11.PNG)

**Comment by ittehgeps** [comment]
Oh, nvm

**Comment by ittehgeps** [comment]
![reeeeee](https://user-images.githubusercontent.com/36374487/37249977-0c9a0b52-24c0-11e8-8b5f-325bf0bf11e0.PNG)
no, still didn't work lol

**Comment by Quenty** [comment]
Ah, yeah. You had it right the first time. I didn't communicate that well.

To get things to work online, Nevermore needs to be loaded on the server too!

Server:
```lua
--- Main injection point for the game
-- @script ServerMain

local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

print("Server loaded")
```

This is required to make Nevermore load up modules and server them to the client!

Client needs to do this:
```lua
--- Main injection point for the game on the client
-- @script ClientMain

local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

local Players = game:GetService("Players")

local localPlayer = Players.LocalPlayer
local playerGui = localPlayer:WaitForChild("PlayerGui")

local snackbarManager = require("SnackbarManager").new()
	:WithPlayerGui(playerGui)

snackbarManager:MakeSnackbar("Client loaded")
print("Client loaded")
```

Here's an example:
[ExamplePlace.zip](https://github.com/Quenty/NevermoreEngine/files/1800874/ExamplePlace.zip)

**Comment by ittehgeps** [comment]
well, your example didn't work but i got it working..

**Comment by ittehgeps** [comment]
the same thing happened as before, except there is no error this time: 
![fsfsf](https://user-images.githubusercontent.com/36374487/37259454-e7c7fddc-255c-11e8-8d6c-6ef7de86bc30.PNG) the snackbar appears and doesn't change transparency or doesn't disappear.

**Comment by ittehgeps** [comment]
sorry for my bad grammar..

**Comment by Quenty** [comment]
You should use `SnackbarManager`!

**Attachment:** [place_with_snackbarManager.zip](https://github.com/Quenty/NevermoreEngine/files/1800980/place_with_snackbarManager.zip)

```lua

--- Main injection point for the game on the client
-- @script ClientMain

local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

local Players = game:GetService("Players")

local localPlayer = Players.LocalPlayer
local playerGui = localPlayer:WaitForChild("PlayerGui")

local snackbarManager = require("SnackbarManager").new()
	:WithPlayerGui(playerGui)

snackbarManager:MakeSnackbar("Nevermore loaded")
print("Client loaded")

```

**Comment by ittehgeps** [comment]
thanks
