### ISSUE TITLE
Datastore retry is no longer best practice

### ISSUE THREAD

**Issue by Quenty** [Quenty/NevermoreEngine#96]

**Comment by Kampfkarren** [comment]
What do you mean?

**Comment by Dollar-500** [comment]
I’ve been wondering about this as well

**Comment by Quenty** [comment]
Roblox automatically retries now, so retrying again is useless.

**Comment by Dollar-500** [comment]
> Roblox automatically retries now, so retrying again is useless.

I thought this feature hasn't been enabled yet...

**Comment by Kampfkarren** [comment]
[It isn't enabled.](https://devforum.roblox.com/t/datastores-automatic-retry/42326/32?u=kampfkarren)

**Comment by Quenty** [comment]
Ah, closed!
